# Generated by Django 5.1 on 2024-08-31 13:34

import core.reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0002_alter_product_options_alter_product_author_and_more'),
        ('core_reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='The review text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='edited',
            field=models.BooleanField(default=False, help_text='Indicates if the review has been edited'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core_product.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, help_text='Rating from 1 to 5', validators=[core.reviews.models.validate_rating]),
        ),
        migrations.AlterModelTable(
            name='review',
            table='core_reviews',
        ),
    ]
